AWSTemplateFormatVersion: '2010-09-09'

Description: ECS Cluster Application Release

Parameters:
  Name:
    Type: String
    Description: Name of this Application
    ConstraintDescription: Must be DNS friendly
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9\-]+$
  ClusterName:
    Type: String
    Description: Name of the ECS cluster to use
    ConstraintDescription: Must be DNS friendly
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9\-]+$
  Environment:
    Description: Environment
    Type: String
    Default: Dev
  Version:
    Type: String
  HealthCheckPath:
    Description: Healthcheck Path used on TargetGroup
    Type: String
    Default: /
  HealthCheckGracePeriod:
    Description: The period of time, in seconds, that the Amazon ECS service scheduler ignores unhealthy Elastic Load Balancing target health checks after a task has first started.
    Type: Number
    Default: 60
  HealthCheckTimeout:
    Description: The amount of time, in seconds, during which no response means a failed health check (2-120 seconds).
    Type: Number
    Default: 5
  HealthCheckInterval:
    Description: The approximate amount of time between health checks of an individual target (5-300 seconds).
    Type: Number
    Default: 10
  TaskDefinitionArn:
    Description: ARN of Task Definition revision to Deploy to this service
    Type: String
  ContainerPort:
    Description: Port container listens
    Type: String
  RulePriority:
    Description: Listerner Rule Priority
    Type: Number
  DeregistrationDelay:
    Description: Target Group Deregistration Delay timeout in seconds
    Type: Number
    Default: 30
  Autoscaling:
    Description: Enable Autoscaling
    Type: String
    Default: Disable
    AllowedValues:
      - Enable
      - Disable
  AutoscalingTargetValue:
    Description: Target CPU for Autoscaling
    Type: Number
    Default: 75
  AutoscalingMaxSize:
    Description: Max number of containers to autoscale
    Type: Number
    Default: 16
  AutoscalingMinSize:
    Description: Min number of containers to autoscale
    Type: Number
    Default: 2
  AlbScheme:
    Description: Is the ALB internal or internet-facing?
    Type: String
  HostedZoneName:
    Type: String
    Description: Hosted Zone name for domain record created for this app

Conditions:
  isAutoscaling: !Equals [ !Ref Autoscaling, 'Enable']
  isInternal: !Equals
    - !Ref AlbScheme
    - 'internal'

Resources:
  AlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: !Ref HealthCheckInterval
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: !Ref HealthCheckTimeout
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: !Ref DeregistrationDelay
      VpcId:
        Fn::ImportValue: !Sub "TfExport-Ecs-${ClusterName}-VpcId"


  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn:
            Ref: AlbTargetGroup
      Conditions:
        - Field: host-header
          Values:
            - !Sub "${Name}-${Version}.*"
      ListenerArn: 
        Fn::ImportValue: !Sub "TfExport-Ecs-${ClusterName}-AlbListenerHttpsArn"
      Priority: !Ref RulePriority

  EcsService:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      TaskDefinition: !Ref TaskDefinitionArn
      DesiredCount: 1
      PlacementStrategies:
        - Type: spread
          Field:  attribute:ecs.availability-zone
        - Type: binpack
          Field: memory
      HealthCheckGracePeriodSeconds: !Ref HealthCheckGracePeriod
      Cluster: 
        Fn::ImportValue: !Sub "TfExport-Ecs-${ClusterName}-EcsName"
      Role: 
        Fn::ImportValue: !Sub "TfExport-Ecs-${ClusterName}-EcsServiceIamRoleArn"
      LoadBalancers:
        - ContainerName: !Sub "${Name}"
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref AlbTargetGroup

  ServiceScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: isAutoscaling
    Properties:
      MaxCapacity: !Ref AutoscalingMaxSize
      MinCapacity: !Ref AutoscalingMinSize
      ResourceId: !Sub
        - "service/${ECSCluster}/${ServiceName}"
        - ECSCluster: 
            Fn::ImportValue: !Sub "TfExport-Ecs-${ClusterName}-EcsName"
          ServiceName: !GetAtt EcsService.Name
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
  ServiceScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: isAutoscaling
    Properties:
      PolicyName: !Sub '${AWS::StackName}-scale-target'
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref 'ServiceScalingTarget'
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: !Ref AutoscalingTargetValue
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization

  Route53Alb:
    Type: AWS::Route53::RecordSet
    Condition: isInternal
    Properties:
      Name: !Sub "${Name}-${Version}.${HostedZoneName}"
      HostedZoneName: !Ref HostedZoneName
      Type: A
      AliasTarget:
        HostedZoneId: 
          Fn::ImportValue: !Sub "TfExport-Ecs-${ClusterName}-AlbZoneId"
        DNSName: 
          Fn::ImportValue: !Sub "TfExport-Ecs-${ClusterName}-AlbDnsName"