name: Security

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag dnxsolutions/ecs-deploy:latest

      - name: Scan image
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: dnxsolutions/ecs-deploy:latest
          fail-build: true
          severity-cutoff: critical
          acs-report-enable: true

      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}

      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}